### ISSUE TITLE
Possible collaboration?

### ISSUE THREAD

**Issue by regerohan** [NemoAndrea/freezer-display#1]
Hi Nemo!
This is similar to something I had in mind but for a different application.
And I would like to use your project as a base for that!
Let me know if you need any help to speed things up :)

**Comment by regerohan** [comment]
I was also wondering how you planned to add/update the samples?

**Comment by NemoAndrea** [comment]
Heya, sounds nice! I will add you to the work in progress album so you can check out where I am at. 

I am waiting for some parts to come in (allowing for hopefully a prototype that is functionally complete), and then I will work on the software again. I think in basic form the software will be quite simple; the only thing that really still needs doing is (1) efficient way to display text into buffer and (2) porting the SPI data generation to C or making the python a lot faster.

**Comment by NemoAndrea** [comment]
Oh, and if you have access to a vacuum forming setup - let me know 😉

**Comment by regerohan** [comment]
Yes, I've access to a vacuum forming setup :)
